---
- name: Converge
  hosts: all
  vars:
    ethv_10_net: goerli
    ethv_20_net: prater
    ethv_validator_keys_folder: validator_keys_testing
    ethv_prysm_pre_start_delay: 13
    ethv_monitoring: yes
  tasks:
    - name: "Include ethereum-validator"
      include_role:
        name: "ethereum-validator"
